version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout

      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-29;default;x86

      - android/start-emulator:
          avd-name: myavd
          no-window: true
          restore-gradle-cache-prefix: v1a
      #          test-command: ./gradlew --info test testDebugUnitTestCoverage
      - android/run-tests
      - android/save-gradle-cache:
          cache-prefix: v1a

      - store_artifacts:
          path: RxJavaExtensions/build/reports
          destination: reports

      - store_test_results:
          path: RxJavaExtensions/build/test-results

      - run:
          name: Test Success
          when: on_success
          command: ./gradlew coveralls

  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "RxJavaExtensions/build.gradle" }}

      - run:
          name: Chmod permissions if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "RxJavaExtensions/build.gradle" }}

      - run:
          name: Build
          command: ./gradlew build

      - run:
          name: Run Lint
          command: ./gradlew lint

      - store_artifacts:
          path: RxJavaExtensions/build/reports
          destination: reports

      - store_test_results:
          path: RxJavaExtensions/build/test-results


workflows:
  test:
    jobs:
      - build
      - test


