version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - 
      - run:
          name: Build
          command: ./gradlew build

      - run:
          name: Run Tests
          command: ./gradlew :RxJavaExtensions:lint :RxJavaExtensions:testDebugUnitTest

      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports

      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
