version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout

      - run:
          name: Build
          command: ./gradlew build

      - run:
          name: Run Tests
          command: ./gradlew :RxJavaExtensions:lint :RxJavaExtensions:testDebugUnitTest

      - store_artifacts:
          path: RxJavaExtensions/build/reports
          destination: reports

      - store_test_results:
          path: RxJavaExtensions/build/test-results
