version: 2.1

orbs:
  android: circleci/android@1.0.2

jobs:
  test:
    executor:
      name: android/android-machine
      resource-class: medium
    steps:
      - checkout
    
      - android/start-emulator-and-run-tests:
          verbose: true
          avd-name: myavd
          no-window: true
          no-audio: true
          no-boot-anim: true
          restore-gradle-cache-prefix: v1a
          wait-for-emulator: true        
          system-image: system-images;android-29;default;x86   
          test-command: ./gradlew test createDebugCoverageReport

      - android/save-gradle-cache:
          cache-prefix: v1a

      - store_artifacts:
          path: RxJavaExtensions/build/reports
          destination: reports

      - store_test_results:
          path: RxJavaExtensions/build/test-results

      - run:
          name: Test Success
          when: on_success
          command: ./gradlew coveralls

  build:
    executor: android/android

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "RxJavaExtensions/build.gradle" }}
            
      - run:
          name: Chmod permissions if permission for Gradlew Dependencies fail, use this. 
          command: sudo chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies    

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "RxJavaExtensions/build.gradle" }}
                      
      - run:
          name: Build
          command: ./gradlew build

      - run:
          name: Run Lint
          command: ./gradlew lint

      - store_artifacts:
          path: RxJavaExtensions/build/reports
          destination: reports

      - store_test_results:
          path: RxJavaExtensions/build/test-results


workflows:
  test:
    jobs:
      - build
      - test

#      - android/run-ui-tests:
#          executor:
#            name: android/android-machine
#            resource-class: medium
#          wait-for-emulator: true
#          test-command: ./gradlew connectedCheck createDebugCoverageReport
#          system-image: system-images;android-28;default;x86

          